export const INQUIRY_TYPES = [
  { id: "job", label: "Job Opportunity", icon: "Briefcase" },
  { id: "freelance", label: "Freelance Project", icon: "Code2" },
  { id: "collaboration", label: "Collaboration", icon: "Users" },
  { id: "consultation", label: "Consultation", icon: "MessageSquare" },
  { id: "internship", label: "Internship", icon: "GraduationCap" },
  { id: "startup", label: "Startup Project", icon: "Rocket" },
  { id: "enterprise", label: "Enterprise Solution", icon: "Building2" },
  { id: "other", label: "Other", icon: "MoreHorizontal" },
];

export const SOCIAL_LINKS = [
  {
    id: "github",
    name: "GitHub",
    description: "View my open-source projects",
    icon: "Github",
    url: "https://github.com/dhanush200322",
    ariaLabel: "Visit my GitHub profile",
  },
  {
    id: "gumroad",
    name: "Gumroad",
    description: "Digital products & templates",
    icon: "Gumroad",
    url: "https://gumroad.com/products",
    ariaLabel: "Visit my Gumroad store",
  },
  {
    id: "fiverr",
    name: "Fiverr",
    description: "Freelance services & custom gigs",
    icon: "Fiverr",
    url: "https://www.fiverr.com/dhanushav318?public_mode=true",
    ariaLabel: "Visit my Fiverr profile",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    description: "Let's connect professionally",
    icon: "Linkedin",
    url: "https://www.linkedin.com/in/dhanush-av-618271378/",
    ariaLabel: "Visit my LinkedIn profile",
  },
  {
    id: "resume",
    name: "Resume",
    description: "Download my official CV",
    icon: "FileText",
    url: "/resume.pdf", 
    ariaLabel: "Download my resume",
  },
  {
    id: "email",
    name: "Email",
    description: "ro224313@gmail.com",
    icon: "Mail",
    url: "mailto:ro224313@gmail.com",
    ariaLabel: "Send me an email",
  },
];
